FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Set environment variables
ENV PORT=3000
ENV CHOKIDAR_USEPOLLING=true
ENV WDS_SOCKET_PORT=0

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "start"] 