repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        files: "\\.(js|jsx|ts|tsx|css|scss|json)$"
        additional_dependencies:
          - prettier@2.8.8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
      - id: eslint
        files: '\\.(js|jsx|ts|tsx)$'
        additional_dependencies:
          - eslint@8.38.0
          - eslint-plugin-react@7.32.2
          - eslint-plugin-react-hooks@4.6.0
          - eslint-config-prettier@8.8.0
          - eslint-plugin-prettier@4.2.1
          - prettier@2.8.8
          - "@typescript-eslint/eslint-plugin@5.59.0"
          - "@typescript-eslint/parser@5.59.0"
          - typescript@5.0.4 