: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.docker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - WEB3_PROVIDER_URI=${WEB3_PROVIDER_URI}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
      - REACT_APP_CONTRACT_ADDRESS=${CONTRACT_ADDRESS}

  # Local Ethereum Node (Hardhat)
  hardhat:
    build: ./ethereum
    volumes:
      - ./ethereum:/app
      - /app/node_modules
    ports:
      - "8545:8545"
    command: npx hardhat node

  # Adminer for database management (optional)
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: 