site_name: SmartRent Documentation
site_description: Documentation for the SmartRent blockchain-based property rental platform
site_author: SmartRent Team
site_url: https://docs.smartrent.com

# Repository
repo_name: DITreneris/smart-rent
repo_url: https://github.com/DITreneris/smart-rent
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 SmartRent

# Configuration
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  language: en

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
  - social

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DITreneris/smart-rent
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/smartrent
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/smartrent

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: quickstart.md
    - Demo Features: demo/README.md
    - FAQs: faq.md
  - User Guide:
    - Overview: user/README.md
    - Landlord Guide: user/landlord.md
    - Tenant Guide: user/tenant.md
    - Admin Guide: user/admin.md
  - Developer Guide:
    - Overview: developer/README.md
    - Setup: developer/setup.md
    - Architecture: developer/architecture.md
    - Database Schema: developer/database.md
    - Testing: developer/testing.md
  - API Reference:
    - Overview: api/README.md
    - Authentication: api/auth.md
    - Properties: api/properties.md
    - Users: api/users.md
    - Transactions: api/transactions.md
  - Quality Assurance:
    - Overview: quality/README.md
    - QA Process: quality/process.md
    - Testing Standards: quality/testing-standards.md
    - Test Strategy: quality/test-strategy.md
    - Code Review: quality/code-review.md
    - Quality Metrics: quality/metrics.md
  - Contributing:
    - How to Contribute: contributing/README.md
    - Code Style: contributing/code-style.md
    - Pull Requests: contributing/pull-requests.md
  - Deployment:
    - Local: deployment/local.md
    - Staging: deployment/staging.md
    - Production: deployment/production.md
    - Documentation: deployment/documentation.md 