apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: smartrent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/username/smartrent:main-frontend
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "/api/v1"
        - name: REACT_APP_CONTRACT_ADDRESS
          valueFrom:
            secretKeyRef:
              name: smartrent-secrets
              key: contract_address
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 20
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m" 